default: &defaults
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  database: <%= Settings.db.name %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
